version: '2.1'

services:
    nginx:
        image: nginx:latest
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./logs/nginx:/var/log/nginx:rw
        volumes_from:
            - app:ro
        depends_on:
            - php
            - app
        restart: "${APP_RESTART}"

    php:
        build: ./php/
        expose:
            - "9000"
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
        volumes_from:
            - app:rw
        depends_on:
            - app
        restart: "${APP_RESTART}"

    app:
        image: php:7-fpm
        volumes:
            - "${APP_ROOT}:/var/www/html:rw"
        command: 'true'
        restart: "${APP_RESTART}"

    database:
        image: mysql:latest
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        expose:
            - "3306"
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        restart: "${APP_RESTART}"

volumes:
    data:
